# Generated by Django 4.2 on 2026-05-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='文章标题')),
                ('category', models.CharField(max_length=50, verbose_name='文章分类')),
                ('tags', models.CharField(blank=True, max_length=200, verbose_name='文章标签')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='封面图片')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布')], default='draft', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
    ]
