# Generated by Django 4.2 on 2026-06-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='github_url',
            field=models.URLField(blank=True, verbose_name='GitHub 链接'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weibo_url',
            field=models.URLField(blank=True, verbose_name='微博链接'),
        ),
    ]
