# Generated by Django 4.2 on 2026-06-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('private', '仅自己可见'), ('public', '公开')], default='private', max_length=20, verbose_name='可见范围'),
        ),
    ]
