# Generated by Django 4.2 on 2026-06-27 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0009_privatemessage_friendship_friendrequest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='blog.post', verbose_name='收藏文章')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_favorites', to=settings.AUTH_USER_MODEL, verbose_name='收藏用户')),
            ],
            options={
                'verbose_name': '文章收藏',
                'verbose_name_plural': '文章收藏',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('comment_on_post', '文章评论'), ('reply_to_comment', '评论回复'), ('friend_request_received', '收到好友申请'), ('friend_request_accepted', '好友申请通过'), ('private_message', '私信')], max_length=40, verbose_name='通知类型')),
                ('message', models.CharField(max_length=255, verbose_name='通知内容')),
                ('target_url', models.CharField(blank=True, max_length=255, verbose_name='跳转地址')),
                ('is_read', models.BooleanField(default=False, verbose_name='已读')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='通知时间')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='触发用户')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='blog.comment', verbose_name='相关评论')),
                ('friend_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='blog.friendrequest', verbose_name='相关好友申请')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='blog.post', verbose_name='相关文章')),
                ('private_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='blog.privatemessage', verbose_name='相关私信')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='接收者')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='postfavorite',
            constraint=models.UniqueConstraint(fields=('user', 'post'), name='unique_post_favorite'),
        ),
    ]
