# Generated by Django 4.2 on 2026-07-06 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0011_registrationrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='文章标题')),
                ('category', models.CharField(max_length=50, verbose_name='文章分类')),
                ('tags', models.CharField(blank=True, max_length=200, verbose_name='文章标签')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布')], max_length=20, verbose_name='状态')),
                ('visibility', models.CharField(choices=[('private', '仅自己可见'), ('public', '公开')], max_length=20, verbose_name='可见范围')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='保存时间')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_revisions', to=settings.AUTH_USER_MODEL, verbose_name='编辑者')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='blog.post', verbose_name='文章')),
            ],
            options={
                'verbose_name': '文章版本',
                'verbose_name_plural': '文章版本',
                'ordering': ['-created_at'],
            },
        ),
    ]
