# Generated by Django 4.2 on 2026-07-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_postrevision'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='series_order',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='系列顺序'),
        ),
        migrations.AddField(
            model_name='post',
            name='series_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='文章系列'),
        ),
        migrations.AddField(
            model_name='postrevision',
            name='series_order',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='系列顺序'),
        ),
        migrations.AddField(
            model_name='postrevision',
            name='series_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='文章系列'),
        ),
    ]
