# Generated by Django 4.2 on 2026-07-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_postreaction_postlike_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('comment_on_post', '文章评论'), ('reply_to_comment', '评论回复'), ('mention', '提到我'), ('friend_request_received', '收到好友申请'), ('friend_request_accepted', '好友申请通过'), ('private_message', '私信')], max_length=40, verbose_name='通知类型'),
        ),
    ]
