# Generated by Django 4.2 on 2026-07-06 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0016_comment_is_hidden_comment_moderated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='屏蔽时间')),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by_users', to=settings.AUTH_USER_MODEL, verbose_name='被屏蔽人')),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocking_users', to=settings.AUTH_USER_MODEL, verbose_name='屏蔽人')),
            ],
            options={
                'verbose_name': '用户屏蔽',
                'verbose_name_plural': '用户屏蔽',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='userblock',
            constraint=models.UniqueConstraint(fields=('blocker', 'blocked'), name='unique_user_block_direction'),
        ),
        migrations.AddConstraint(
            model_name='userblock',
            constraint=models.CheckConstraint(check=models.Q(('blocker', models.F('blocked')), _negated=True), name='user_block_users_differ'),
        ),
    ]
