# Generated by Django 4.2 on 2026-07-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_userblock_userblock_unique_user_block_direction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='scheduled_publish_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='定时发布时间'),
        ),
        migrations.AddField(
            model_name='postrevision',
            name='scheduled_publish_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='定时发布时间'),
        ),
    ]
