# Generated by Django 4.2 on 2026-07-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_post_scheduled_publish_at'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', 'is_hidden', '-created_at'], name='comment_post_hidden_idx'),
        ),
        migrations.AddIndex(
            model_name='friendrequest',
            index=models.Index(fields=['receiver', 'status', '-updated_at'], name='friendreq_recv_status_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read', '-created_at'], name='notif_rec_read_created_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'notification_type', '-created_at'], name='notif_rec_type_created_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['status', 'visibility', '-created_at'], name='post_status_vis_created_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author', 'status', '-created_at'], name='post_author_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['status', 'category', '-created_at'], name='post_category_created_idx'),
        ),
        migrations.AddIndex(
            model_name='privatemessage',
            index=models.Index(fields=['recipient', 'is_read', 'created_at'], name='pm_rec_read_created_idx'),
        ),
        migrations.AddIndex(
            model_name='privatemessage',
            index=models.Index(fields=['sender', 'recipient', 'created_at'], name='pm_pair_created_idx'),
        ),
        migrations.AddIndex(
            model_name='registrationrequest',
            index=models.Index(fields=['status', '-updated_at'], name='regreq_status_updated_idx'),
        ),
    ]
