# Generated by Django 4.2 on 2026-07-10 13:29

import blog.models
import blog.protected_storage
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0019_comment_comment_post_hidden_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('image', models.ImageField(storage=blog.protected_storage.ProtectedMediaStorage(), upload_to=blog.models.post_image_upload_path, verbose_name='图片')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='原文件名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': '文章正文图片',
                'verbose_name_plural': '文章正文图片',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RateLimitState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64, verbose_name='操作')),
                ('key_hash', models.CharField(max_length=64, verbose_name='匿名键')),
                ('window_started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='窗口开始时间')),
                ('request_count', models.PositiveIntegerField(default=0, verbose_name='请求次数')),
                ('blocked_until', models.DateTimeField(blank=True, null=True, verbose_name='阻止截止时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '请求限流状态',
                'verbose_name_plural': '请求限流状态',
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(blank=True, null=True, storage=blog.protected_storage.ProtectedMediaStorage(), upload_to='covers/', verbose_name='封面图片'),
        ),
        migrations.AddIndex(
            model_name='ratelimitstate',
            index=models.Index(fields=['-updated_at'], name='ratelimit_updated_idx'),
        ),
        migrations.AddConstraint(
            model_name='ratelimitstate',
            constraint=models.UniqueConstraint(fields=('action', 'key_hash'), name='unique_rate_limit_action_key'),
        ),
        migrations.AddField(
            model_name='postimage',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_images', to=settings.AUTH_USER_MODEL, verbose_name='上传者'),
        ),
        migrations.AddField(
            model_name='postimage',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='body_images', to='blog.post', verbose_name='关联文章'),
        ),
        migrations.AddIndex(
            model_name='postimage',
            index=models.Index(fields=['owner', '-created_at'], name='postimage_owner_created_idx'),
        ),
    ]
