# Generated by Django 4.2 on 2026-07-10 13:34

from django.db import migrations, models
import django.db.models.deletion
import re


def populate_normalized_tags(apps, schema_editor):
    Post = apps.get_model('blog', 'Post')
    Tag = apps.get_model('blog', 'Tag')
    PostTag = apps.get_model('blog', 'PostTag')

    for post in Post.objects.exclude(tags='').iterator():
        normalized_tags = {}
        for raw_tag in re.split(r'[,，;；\s]+', post.tags or ''):
            tag_name = raw_tag.strip()[:50]
            normalized_name = tag_name.casefold()[:150]
            if normalized_name and normalized_name not in normalized_tags:
                normalized_tags[normalized_name] = tag_name

        for normalized_name, tag_name in normalized_tags.items():
            tag, _ = Tag.objects.get_or_create(
                normalized_name=normalized_name,
                defaults={'name': tag_name},
            )
            PostTag.objects.get_or_create(post=post, tag=tag)


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_postimage_ratelimitstate_alter_post_cover_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='标签名')),
                ('normalized_name', models.CharField(max_length=150, unique=True, verbose_name='规范名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PostTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_links', to='blog.post')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_links', to='blog.tag')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='tag_objects',
            field=models.ManyToManyField(blank=True, related_name='posts', through='blog.PostTag', to='blog.tag', verbose_name='规范标签'),
        ),
        migrations.AddIndex(
            model_name='posttag',
            index=models.Index(fields=['tag', 'post'], name='posttag_tag_post_idx'),
        ),
        migrations.AddConstraint(
            model_name='posttag',
            constraint=models.UniqueConstraint(fields=('post', 'tag'), name='unique_post_tag'),
        ),
        migrations.RunPython(populate_normalized_tags, migrations.RunPython.noop),
    ]
