# Generated by Django 4.2 on 2026-07-10 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0021_tag_posttag_post_tag_objects_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('task_type', models.CharField(choices=[('prepare_music_playback', '生成音乐播放版'), ('generate_homepage_copy', '生成首页文案')], max_length=64, verbose_name='任务类型')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '执行中'), ('succeeded', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('output', models.TextField(blank=True, verbose_name='输出')),
                ('error_message', models.TextField(blank=True, verbose_name='错误')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='background_tasks', to=settings.AUTH_USER_MODEL, verbose_name='发起人')),
            ],
            options={
                'verbose_name': '后台任务',
                'verbose_name_plural': '后台任务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='backgroundtask',
            index=models.Index(fields=['status', 'created_at'], name='bgtask_status_created_idx'),
        ),
    ]
