# Generated by Django 5.2.15 on 2026-07-12 06:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_backgroundtask_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='series_title',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='文章系列'),
        ),
        migrations.AddIndex(
            model_name='postfavorite',
            index=models.Index(fields=['user', '-created_at'], name='postfav_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='postrevision',
            index=models.Index(fields=['post', '-created_at'], name='postrev_post_created_idx'),
        ),
    ]
