from django.contrib.staticfiles.apps import StaticFilesConfig


class CloverStaticFilesConfig(StaticFilesConfig):
    ignore_patterns = [
        *StaticFilesConfig.ignore_patterns,
        '*.map',
        'img/favicon.png',
        'img/favicon_v2.png',
        'img/favicon_v3.png',
        'img/stain_gate.jpg',
        'plugins/bootstrap-5.3.8-dist/css/bootstrap-grid*',
        'plugins/bootstrap-5.3.8-dist/css/bootstrap-reboot*',
        'plugins/bootstrap-5.3.8-dist/css/bootstrap-utilities*',
        'plugins/bootstrap-5.3.8-dist/css/bootstrap.css',
        'plugins/bootstrap-5.3.8-dist/css/bootstrap.rtl*',
        'plugins/bootstrap-5.3.8-dist/js/bootstrap.bundle.js',
        'plugins/bootstrap-5.3.8-dist/js/bootstrap.esm*',
        'plugins/bootstrap-5.3.8-dist/js/bootstrap.js',
        'plugins/bootstrap-5.3.8-dist/js/bootstrap.min.js',
        'plugins/fontawesome-free-7.1.0-web/js/*',
        'plugins/fontawesome-free-7.1.0-web/css/all.css',
        'plugins/fontawesome-free-7.1.0-web/css/brands*',
        'plugins/fontawesome-free-7.1.0-web/css/fontawesome*',
        'plugins/fontawesome-free-7.1.0-web/css/regular*',
        'plugins/fontawesome-free-7.1.0-web/css/solid*',
        'plugins/fontawesome-free-7.1.0-web/css/svg*',
        'plugins/fontawesome-free-7.1.0-web/css/v4-*',
        'plugins/fontawesome-free-7.1.0-web/css/v5-*',
        'plugins/fontawesome-free-7.1.0-web/metadata/*',
        'plugins/fontawesome-free-7.1.0-web/scss/*',
        'plugins/fontawesome-free-7.1.0-web/sprites/*',
        'plugins/fontawesome-free-7.1.0-web/sprites-full/*',
        'plugins/fontawesome-free-7.1.0-web/svgs/*',
        'plugins/fontawesome-free-7.1.0-web/svgs-full/*',
        'plugins/fontawesome-free-7.1.0-web/LICENSE.txt',
    ]
